### ISSUE TITLE
Aesthetic change

### ISSUE THREAD

**Issue by wallace11** [laggardkernel/ranger-fzf-marks#1]
What's your opinion about dropping the use of `--height 62%` in `fzf` command? Without it, it looks much cleaner.

Here's a comparison to make my point clearer:  
With:
![image](https://user-images.githubusercontent.com/5497761/75109413-017f6300-5666-11ea-95e8-444452aa8812.png)

Without:
![image](https://user-images.githubusercontent.com/5497761/75109420-1bb94100-5666-11ea-8547-cea8ab9ae1bd.png)

**Comment by laggardkernel** [comment]
Sorry, haven't update the plugin for a long time. Just add some customization through environment variables.

The default `--height` is removed, and you can customize the layout with `FZF_FZM_OPTS` and `FZF_DMARK_OPTS`. Check the `README` for detail.
